name: Merge to main branch
# событие экшена
on: 
  workflow_dispatch:
  push:
    branches:
      - main
  # pull_request:
  #   types:
  #     - opened
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ghcr.io/${{ github.repository }}:latest

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # авторизация в docker hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      
      - name: Deploy to VPS and build
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          ENV_CONTENT: ${{ secrets.ENV_PROD }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd /root/github/mailing_bot && \
            echo '$ENV_CONTENT' > .env.dev && \
            echo 'IMAGE_TAG=$IMAGE_TAG' >> .env.dev && \
            git checkout main && \
            git pull origin main && \
            sudo apt update && sudo apt install make -y && \
            make stop-prod && \
            make build-prod
          " 
            
      - name: Waiting up containers
        run: sleep 5

      - name: Make migrate
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          cd /root/github/mailing_bot && docker-compose exec -T app make migrate
          "

      

      





      


 
