name: Merge to stage branch
# событие экшена
on: 
  workflow_dispatch:
  push:
    branches:
      # - dev
      - 'release/**'
  # pull_request:
  #   types:
  #     - opened
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  # IMAGE_TAG: ghcr.io/${{ github.repository }}:latest

jobs: 
  extract-release-tag:
    runs-on: ubuntu-latest
    outputs:
      release-tag: ${{ steps.extract-tag.outputs.release-tag }}
    steps:
      - name: Extract release tag from branch name
        id: extract-tag
        run: |
          if [[ "${{ github.ref }}" == refs/heads/release/* ]]; then
            RELEASE_TAG=$(echo "${{ github.ref }}" | sed 's|refs/heads/release/||')
            echo "release-tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
          else
            echo "release-tag=latest" >> $GITHUB_OUTPUT
          fi 
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read      # Чтобы скачать код
      packages: write     # Чтобы пушить Docker образ в GHCR

    steps:
    - name: Get repository code
      uses: actions/checkout@v4

    # авторизация с реестр github
    - name: Login to Github registry
      uses: docker/login-action@v3
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.extract-release-tag.outputs.release-tag }}

        
  test:
    services:      
      db_testing:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5435:5432

    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read      
      packages: write     

    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Wait for PostgreSQL
        run: |
          until nc -z localhost 5435; do sleep 2; done
          echo "✅ PostgreSQL is ready"
      
      - name: Login to Github registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull app image from registry
        run: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.extract-release-tag.outputs.release-tag }}

      - name: Create .env file from secrets
        run: echo "$ENV_CONTENT" > .env.dev
        env:
          ENV_CONTENT: ${{ secrets.ENV_DEV }}

      - name: Run app with env file
        run: |
          docker run -d \
            --name app-container \
            --network host \
            --env-file .env.dev \
            -e POSTGRES_HOST_TESTING=localhost \
            -p 3000:3000 \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.extract-release-tag.outputs.release-tag }}

      - name: Waiting up containers
        run: sleep 5

      - name: Run test
        run: docker exec app-container make test

      - name: delete old packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: container
          min-versions-to-keep: 2
          token: ${{ secrets.GITHUB_TOKEN }}
          # delete-only-untagged-versions: false   
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # авторизация в docker hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      
      - name: Deploy to VPS and build
        env:
          IMAGE_TAG: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.extract-release-tag.outputs.release-tag }}
          RELEASE_TAG: ${{ needs.extract-release-tag.outputs.release-tag }}
          ENV_CONTENT: ${{ secrets.ENV_DEV }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd /root/github/mailing_bot && \
            echo '$ENV_CONTENT' > .env.dev && \
            echo 'IMAGE_TAG=$IMAGE_TAG' >> .env.dev && \
            git fetch origin && \


            if [[ '$IMAGE_TAG' != 'latest' ]]; then
              git checkout release/$RELEASE_TAG || git checkout -b release/$RELEASE_TAG origin/release/$RELEASE_TAG
              git pull origin release/$RELEASE_TAG
            else
              git checkout dev || git checkout -b dev origin/dev
              git pull origin dev
            fi  && \

            sudo apt update && sudo apt install make -y && \
            make stop-stage && \
            make build-stage
          " 
            
      - name: Waiting up containers
        run: sleep 5

      - name: Make migrate
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          cd /root/github/mailing_bot && make migrate-dev
          "

      

      





      


 
